config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "report#list"

  get 'report/list'
  get 'report/detail/:entry_id' => "report#detail", as: 'report_detail'
  get 'report/delete/:entry_id' => "report#delete", as: 'report_delete'
  get 'report/search'
  post 'report/add'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entrylog.rb
class Entrylog < ApplicationRecord
	serialize :content, JSON
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  before_action :authenticate_user!, except: :add
  protect_from_forgery

  def list 
    @entries = Entrylog.order("id desc").paginate(page: params[:page], per_page: 5)
    if !params[:search].to_s.empty?
      @entries=@entries.where('content LIKE ?', "%#{params[:search]}%")
    end
  end

  def detail
    begin
      entry_id = params[:entry_id]
      @data = Entrylog.find(entry_id) 
      @stacktrace = @data.content["STACK_TRACE"]
      @data = @data.as_json
    rescue Exception => e
      Rails.logger.info " ⚠️  #{e}"
      redirect_to report_list_path
    end
  end

  def delete
    entry_id = params[:entry_id]
    begin
      entry = Entrylog.find(entry_id) 
      entry.delete
      flash[:notice] = "Record deleted"
    rescue Exception => e
      Rails.logger.info " ⚠️  #{e}"
      flash[:alert] = "⚠️ #{e}"
    end
    redirect_to report_list_path
  end

  def search
  end

  def add
    response =  'TOKEN ERROR' 
    status = 401
    if params[:register_token] == ENV["REGISTER_TOKEN"] 
      save_record(params)
      send_email(params)
      status = 200
      response =  'CREATED' 
    else
      Rails.logger.warn "#{params[:register_token]} == #{ENV["REGISTER_TOKEN"]}" 
    end
  respond_to do |format|  ## Add this
    format.any { render :json => {:response => response },content_type: 'application/json', :status => status  }
  end        
  end

  private

  def save_record(data)
      record = Entrylog.new
      record.content = params
      record.report_id = params["REPORT_ID"]
      record.save
      response =  'SAVED' 
  end

  def send_email(data)
      hdata = data.as_json
      if !ENV["SMTP_URI"].to_s.empty?
        EntryMailer.notification_email(hdata).deliver_now
      else
        Rails.logger.warn "send_email: #{!ENV["SMTP_URI"].to_s.empty?}"     
      end
  end

  def send_slack(data)
    # ToDo
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acrylic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
  </head>

  <body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">ACRylic</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
<% if user_signed_in? %>
  <li class="nav-item">
    <%= form_tag(report_list_path, method: :get) %>
     <input  class= "nav-link" style="color:gray" type="text" placeholder="search" name="search">   
     </form>
  </li>
  <li class="nav-item">
  <%= link_to('Start', report_list_path, class: "nav-link") %>        
  </li>
  <li class="nav-item">
  <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>        
  </li>
<% else %>
  <li class="nav-item">
  <%= link_to('Login', new_user_session_path, class: "nav-link") %>  
  </li>
<% end %>
        </ul>
      </div>
    </div>
  </nav>

<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">

      <% if !notice.to_s.empty? %>
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      <% end %>
      
      <% if !alert.to_s.empty? %>
        <div class="alert alert-warning" role="alert">
          <%= alert %>
        </div>
      <% end %>

    <%= yield %>


    </div>
  </div>
</div>

  </body>
</html>

app/views/report/add.html.erb
<h1>Report#add</h1>
<p>Find me in app/views/report/add.html.erb</p>

app/views/report/delete.html.erb
<h1>Report#delete</h1>
<p>Find me in app/views/report/delete.html.erb</p>

app/views/report/detail.html.erb
<br/><br/>
    <h2>STACK TRACE</h2>
      <pre style="text-align:left">
<%=@stacktrace%>
      </pre>
    <h2>FULL TRACE</h2>
    <div style="text-align: left">
      <%= (ap @data).html_safe %> 
    </div>

app/views/report/list.html.erb
<br/><br/>

  <div class="row">
    <div class="col-lg-12 text-center">
        <%= will_paginate @entries %>
    </div>
  </div>
  <br/>
        <table align="center" width="90%">
        	<tr>
            <th> </th>
            <th> </th>
            <th><%= fa_icon "id-card" %></th>
        		<th><%= fa_icon "history" %></th>
        		<th><%= fa_icon "gift" %></th>
        		<th><%= fa_icon "android" %></th>
        		<th><%= fa_icon "mobile" %></th>
        		<th><%= fa_icon "fire" %></th>
        	</tr>
        	<% @entries.each do |entry| %>
        		<tr>
            <th><%=link_to (fa_icon "search"),report_detail_path(entry.id) %> </th>
            <th><%=link_to (fa_icon "trash"), report_delete_path(entry.id) %> </th>
        			<td><%= entry.id %></td>
        			<td><%= entry.created_at %></td>
        			<td><%= entry.content["APP_VERSION_NAME"] rescue "" %></td>
        			<td><%= entry.content["ANDROID_VERSION"] rescue "" %></td>
        			<td>
        				<%= entry.content["BUILD"]["MANUFACTURER"] rescue "" %>
        				<%= entry.content["BUILD"]["MODEL"] rescue "" %>
        			</td>
        			<td ><pre style="margin-left: 10px;" align="left"><%= entry.content["STACK_TRACE"] rescue "" %></pre></td>
        		</tr>	
        	<% end %>

        </table>
  <div class="row">
    <div class="col-lg-12 text-center">
        <%= will_paginate @entries %>
    </div>
  </div>

app/views/report/search.html.erb
<h1>Report#search</h1>
<p>Find me in app/views/report/search.html.erb</p>